version: 0.2

env:
  variables:
    POSTGRES_USER: "postgres_user"
    POSTGRES_PASSWORD: "postgres_pass"
    POSTGRES_DB: "postgres_db"
    POSTGRES_PORT: "5433"
    POSTGRES_HOST: "localhost"
    STATIC_TOKEN: "static_token"
    ENVIRONMENT: "test"
    SQLALCHEMY_DATABASE_URI: "sqlite:///:memory:"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Instalando dependencias..."
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Ejecutando pruebas unitarias en entorno de prueba con SQLite..."
      - pytest tests/test_blacklist.py
      # CodeBuild se detiene aquí si pytest falla y marca el proceso como fallido
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 183295420248.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...      
      - docker build -t devops/ohio .
      - docker tag devops/ohio:latest 183295420248.dkr.ecr.us-east-2.amazonaws.com/devops/ohio:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 183295420248.dkr.ecr.us-east-2.amazonaws.com/devops/ohio:latest
artifacts:
  files:
    - '**/*'
